
-- Insert the 3 new grillz products
INSERT INTO public.grillz_products (
  stripe_product_id, name, description, price, original_price, category, product_type, 
  color, material, style, gemstone, teeth_count, image_url, rating, review_count, 
  discount_percentage, in_stock, ships_today, featured
) VALUES 
(
  'prod_SinWzWIoeUdbeb', 
  '6 on 6 VVS Moissanite Diamond Grillz', 
  'Premium 6 teeth VVS moissanite diamond grillz set', 
  145900, 
  162100, 
  'Top Grillz', 
  'Moissanite Grillz', 
  'Yellow Gold', 
  '925 Silver', 
  'Iced Out', 
  'VVS Moissanite', 
  '6 Teeth', 
  '/lovable-uploads/bf68e291-8e46-4cdf-8bc1-9ace2278650d.png', 
  5, 
  18, 
  10, 
  true, 
  true, 
  false
),
(
  'prod_SinUIQTFZNLWKa', 
  '8 on 8 Custom Moissanite Diamond Grillz Set', 
  'Custom designed 8 teeth moissanite diamond grillz with premium finish', 
  198900, 
  221000, 
  'Custom Grillz', 
  'Custom Grillz', 
  'White Gold', 
  '925 Silver', 
  'Custom Design', 
  'VVS Moissanite', 
  '8 Teeth', 
  '/lovable-uploads/bf68e291-8e46-4cdf-8bc1-9ace2278650d.png', 
  5, 
  42, 
  10, 
  true, 
  true, 
  true
),
(
  'prod_SinKMPFJVp7xUX', 
  'Full Set VVS Moissanite Diamond Grillz Premium', 
  'Complete top and bottom VVS moissanite diamond grillz set with premium quality', 
  367500, 
  408300, 
  'Full Set Grillz', 
  'Moissanite Grillz', 
  'Rose Gold', 
  'Solid Gold', 
  'Iced Out', 
  'VVS Moissanite', 
  'Full Set', 
  '/lovable-uploads/bf68e291-8e46-4cdf-8bc1-9ace2278650d.png', 
  5, 
  73, 
  10, 
  true, 
  false, 
  true
);
