// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdidixccpcgzbqqawywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkaWRpeGNjcGNnemJxcWF3eXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODQ0MjUsImV4cCI6MjA2Njk2MDQyNX0.SGuKKEJpVfPeANY6uy9E0IylusNqySXV8ZQKQk8D3DI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});